image: randr0id/android-docker

cache:
  key: ${CI_PROJECT_ID}
  paths:
    - .gradle/

stages:
  - test
  - build

before_script:
  - export GRADLE_USER_HOME=$(pwd)/.gradle 
  - chmod +x ./gradlew

lint_test:
  stage: test
  except:
    - tags
  artifacts:
    when: always
    expire_in: 6 months
    paths:
      - fastscroll/build/reports/
  script:
    - ./gradlew lintRelease

merge_build:
  stage: build
  except:
    - schedules
    - web
    - tags
    - main
  script:
    - ./gradlew assembleRelease

release_build:
  stage: build
  only:
    - schedules
    - web
    - main
  artifacts:
    expire_in: 1 year
    paths:
      - fastscroll/build/outputs/aar/
      - fastscroll/build/publications/release/
  script:
    - ./gradlew generateArchives
    - ./gradlew assembleRelease
