name: Build checks

on:
  push:
    branches:
      - '**'

jobs:
  lint:
    name: lintRelease
    runs-on: ubuntu-20.04
    container:
      image: randr0id/android-docker:31
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Lint checks
        run: ./gradlew lintRelease

  build:
    name: assembleRelease
    runs-on: ubuntu-20.04
    container:
      image: randr0id/android-docker:31
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Release build
        run: ./gradlew assembleRelease

  archive:
    name: generateArchives
    runs-on: ubuntu-20.04
    container:
      image: randr0id/android-docker:31
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Generate source and javadoc jars
        run: ./gradlew generateArchives
