name: Build checks

on:
  push:
    branches:
      - '**'

jobs:
  detekt:
    name: detekt
    runs-on: ubuntu-20.04
    container:
      image: randr0id/android-docker:31
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Detekt checks
        run: ./gradlew detekt detektBuildSrc
      - name: Archive Detekt report
        uses: actions/upload-artifact@v2
        with:
          name: detekt-reports
          path: ./**/build/reports/detekt/*.html

  lint:
    name: lintRelease
    runs-on: ubuntu-20.04
    container:
      image: randr0id/android-docker:31
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Lint checks
        run: ./gradlew lintRelease
      - name: Archive Lint report
        uses: actions/upload-artifact@v2
        with:
          name: lint-reports
          path: ./**/build/reports/lint*.html

  build:
    name: assembleRelease
    runs-on: ubuntu-20.04
    container:
      image: randr0id/android-docker:31
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Release build
        run: ./gradlew assembleRelease

  archive:
    name: generateArchives
    runs-on: ubuntu-20.04
    container:
      image: randr0id/android-docker:31
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Generate source and javadoc jars
        run: ./gradlew generateArchives
